name: GitHub Notifications

on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Teams notification
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: |
          if [ "${{ github.event_name }}" == "issues" ]; then
            title="${{ github.event.issue.title }}"
            url="${{ github.event.issue.html_url }}"
            body="${{ github.event.issue.body }}"
            user="${{ github.event.issue.user.login }}"
            type="Issue"
          else
            title="${{ github.event.pull_request.title }}"
            url="${{ github.event.pull_request.html_url }}"
            body="${{ github.event.pull_request.body }}"
            user="${{ github.event.pull_request.user.login }}"
            type="Pull Request"
          fi
          curl -H 'Content-Type: application/json' -d '{
            "@type": "MessageCard",
            "@context": "http://schema.org/extensions",
            "summary": "'"${type} Notification"'",
            "themeColor": "0076D7",
            "title": "New '"${type}"': '"${title}"'",
            "sections": [{
              "activityTitle": "A new '"${type}"' has been created.",
              "activitySubtitle": "'"${type} Title: ${title}"'",
              "activityImage": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
              "facts": [
                {
                  "name": "Repository:",
                  "value": "'${{ github.repository }}'"
                },
                {
                  "name": "Created By:",
                  "value": "'"${user}"'"
                },
                {
                  "name": "Description:",
                  "value": "'"${body}"'"
                }
              ],
              "markdown": true
            }],
            "potentialAction": [{
              "@type": "OpenUri",
              "name": "View '"${type}"'",
              "targets": [{
                "os": "default",
                "uri": "'"${url}"'"
              }]
            }]
          }' $TEAMS_WEBHOOK_URL
